---
# handlers file for ansible_role_microk8s

- name: Refresh certs
  become: yes
  command: microk8s refresh-certs

- name: Restart containerd
  become: yes
  ansible.builtin.service:
    name: snap.microk8s.daemon-containerd
    state: restarted
